# Generated by Django 5.0.14 on 2025-06-27 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('simbolo', models.CharField(blank=True, max_length=5, null=True)),
                ('cod_color', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.IntegerField(unique=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('es_encargado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado_marcaje', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcaje.sucursal')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionEmpleadoEncargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargado_asignado', to='marcaje.empleado')),
                ('encargado', models.ForeignKey(limit_choices_to={'es_encargado': True}, on_delete=django.db.models.deletion.CASCADE, related_name='empleados_asignados', to='marcaje.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='GestionFechaCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('fecha_corte', models.DateField()),
            ],
            options={
                'unique_together': {('anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='Marcaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora de registro')),
                ('tipo_registro', models.CharField(choices=[('I', 'Entrada'), ('O', 'Salida')], max_length=1, verbose_name='Tipo de marcaje')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcaje.empleado', verbose_name='Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='MarcajeDepurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('entrada', models.TimeField(null=True)),
                ('salida', models.TimeField(null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcaje.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_final', models.TimeField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('tiene_comprobante', models.BooleanField(default=False)),
                ('estado_solicitud', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('SB', 'SUBSANADO'), ('R', 'Rechazada')], default='P', max_length=2)),
                ('pendiente_subsanar', models.BooleanField(default=False)),
                ('aprobacion_gerencial', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcaje.empleado')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_enviadas', to='marcaje.empleado')),
                ('tipo_permiso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcaje.tipopermisos')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.FileField(upload_to='')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcaje.permisos')),
            ],
        ),
        migrations.CreateModel(
            name='GestionPermisoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion_realizada', models.CharField(max_length=100)),
                ('revisada_por', models.CharField(max_length=100)),
                ('comentarios', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcaje.permisos')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='asignacionempleadoencargado',
            constraint=models.UniqueConstraint(fields=('empleado',), name='unique_empleado_asignado'),
        ),
    ]
