# Generated by Django 5.0.14 on 2025-07-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0002_alter_permisos_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='nomina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
