# Generated by Django 5.2 on 2025-05-26 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0003_rename_permiso_permisocomprobante_permiso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
