# Generated by Django 5.0.14 on 2025-07-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0003_sucursal_nomina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='nomina',
        ),
    ]
