# Generated by Django 5.2 on 2025-05-29 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0005_alter_empleado_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionempleadoencargado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargado_asignado', to='marcaje.empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gestionpermisodetalle',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='estado_solicitud',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('SB', 'SUBSANADO'), ('R', 'Rechazada')], default='P'),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_solicitud',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='asignacionempleadoencargado',
            constraint=models.UniqueConstraint(fields=('empleado',), name='unique_empleado_asignado'),
        ),
    ]
