# Generated by Django 5.0.14 on 2025-07-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0005_empleado_activo_alter_empleado_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='tipo_nomina',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
