# Generated by Django 5.0.14 on 2025-07-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0006_sucursal_tipo_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='tipo_nomina',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
