# Generated by Django 5.2 on 2025-05-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0006_alter_asignacionempleadoencargado_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='fecha_solicitud',
            field=models.DateField(auto_now=True),
        ),
    ]
