# Generated by Django 5.0.14 on 2025-07-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0007_empleado_tipo_nomina'),
    ]

    operations = [
        migrations.CreateModel(
            name='SucursalTipoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nomina', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='tipo_nomina',
        ),
    ]
