# Generated by Django 5.2 on 2025-05-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0007_alter_permisos_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='pendiente_subsanar',
            field=models.BooleanField(default=False),
        ),
    ]
