# Generated by Django 5.0.14 on 2025-07-07 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0008_sucursaltiponomina_remove_sucursal_tipo_nomina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursaltiponomina',
            old_name='tipo_nomina',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_nomina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='marcaje.sucursaltiponomina'),
        ),
    ]
