# Generated by Django 5.2 on 2025-05-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0008_permisos_pendiente_subsanar'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionFechaCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.DateField(unique_for_year=True)),
                ('mes', models.DateField(unique_for_month=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('fecha_corte', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='permisos',
            name='aprobacion_gerencial',
            field=models.BooleanField(default=False),
        ),
    ]
