# Generated by Django 5.0.14 on 2025-07-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0009_rename_tipo_nomina_sucursaltiponomina_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo_nomina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='SucursalTipoNomina',
        ),
    ]
