# Generated by Django 5.2 on 2025-06-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0009_gestionfechacorte_permisos_aprobacion_gerencial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionfechacorte',
            name='anio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gestionfechacorte',
            name='mes',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='gestionfechacorte',
            unique_together={('anio', 'mes')},
        ),
    ]
