# Generated by Django 5.2 on 2025-06-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0010_alter_gestionfechacorte_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopermisos',
            name='simbolo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_solicitud',
            field=models.DateField(auto_now_add=True),
        ),
    ]
