# Generated by Django 5.0.14 on 2025-07-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0010_alter_empleado_tipo_nomina_delete_sucursaltiponomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='estado_solicitud',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('SB', 'Subsanar'), ('R', 'Rechazada')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
