# Generated by Django 5.0.14 on 2025-07-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0011_alter_permisos_estado_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionpermisodetalle',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcaje.permisos'),
        ),
    ]
