# Generated by Django 5.2 on 2025-06-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0011_tipopermisos_simbolo_alter_permisos_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopermisos',
            name='cod_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
