# Generated by Django 5.0.14 on 2025-07-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0012_alter_gestionpermisodetalle_solicitud'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marcajedepurado',
            unique_together={('empleado', 'fecha')},
        ),
    ]
