# Generated by Django 5.2 on 2025-06-18 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0013_alter_empleado_user_alter_gestionfechacorte_mes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empleado_marcaje', to=settings.AUTH_USER_MODEL),
        ),
    ]
