# Generated by Django 5.0.14 on 2025-07-28 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0013_alter_marcajedepurado_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_disponibles', models.DecimalField(decimal_places=2, max_digits=5)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to='marcaje.empleado')),
            ],
        ),
    ]
