# Generated by Django 5.0.14 on 2025-07-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0014_vacacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
