# Generated by Django 5.2 on 2025-06-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0016_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='hora_final',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permisos',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
