# Generated by Django 5.0.14 on 2025-07-28 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0017_remove_empresa_sucursal_sucursal_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marcaje.sucursal'),
        ),
    ]
