# Generated by Django 5.2 on 2025-06-25 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0017_permisos_hora_final_permisos_hora_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestionpermisodetalle',
            name='fecha',
        ),
        migrations.AddField(
            model_name='gestionpermisodetalle',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
