# Generated by Django 5.0.14 on 2025-07-28 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0018_remove_sucursal_empresa_empresa_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marcaje.empresa'),
        ),
    ]
