# Generated by Django 5.2 on 2025-06-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0018_remove_gestionpermisodetalle_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestionpermisodetalle',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
    ]
