from django.urls import path
from . import views
from marcaje.views import logout_view

urlpatterns = [
    path('', views.lista_registros, name='marcaje'),
    path('sync-empleados/', views.sync_empleados_view, name='sync_empleados'),
    path('api/empleados/', views.empleados_proxy, name='empleados_proxy'),
    path('api/asis/', views.asistencias_api, name='asis_api'),
    path('registrados', views.marcar),
    path('sync-marcaje/', views.sync_marcaje_view, name='sync_marcaje'),
    path('reporte/', views.reporte_asistencia, name='reporte_asistencia'),
    path('validar-asistencia/', views.validar_asistencias, name='validar_asistencia'),
    path('solicitud/', views.solicitud_rh),
    path('crear-permiso/', views.crear_permiso, name='crear_permiso'),
    path('obtener-empleados/', views.obtener_empleados, name='obtener_empleados'),
    path('nomas/<int:encargado_id>/', views.asignar_empleados, name='asignar_empleados'),
    path('convertir_a_encargado/<int:empleado_id>/', views.convertir_a_encargado, name='convertir_a_encargado'),
    path('convertir_a_empleado/<int:empleado_id>/', views.convertir_a_empleado, name='convertir_a_empleado'),
    path('encargados/<int:encargado_id>/', views.get_empleados_por_encargado, name='mostrar_empleados'),
    path('cargar_empleados/', views.cargar_empleados_por_encargado, name='cargar_empleados'),
    path('solicitud-rh/', views.solicitud_rh, name='solicitud_rh'),
    path('solicitudes-encargado/', views.vista_solicitudes_encargado, name='solicitudes_encargado'),
    path('subir_comprobantes/', views.subir_comprobante, name='subir_comprobantes'),
    path('form-comprobantes/<int:permiso_id>/', views.formulario_comprobantes, name="form_comprobante"),
    path('empleados_y_encargados/', views.empleados_y_encargados, name='empleados_y_encargados'),
    path('ver_encargados/', views.ver_encargados, name='ver_encargados'),
    path('asignados/', views.asignar_empleados),
    path('modal-permiso/<int:permiso_comprobante_id>/', views.modal_solicitud, name='modal_solicitud'),
    path('accion-permiso/', views.accion_solicitud, name='accion_solicitud'),
    path('historial-solicitudes/', views.ver_historial_solicitudes, name='historial_solicitudes'),
    path('historial-encargado/', views.ver_historial_encargado, name='historial_encargado'),
    # path('login', views.cargar_login, name='login'),
    path('logout/', logout_view, name='logout'),
    path('crear_usuario/', views.crear_usuario, name='crear_usuario'),
    path('ver/', views.ver_a_cargo, name='ver'),
    path('ficha/<int:permiso_id>/', views.ficha_permiso, name='ficha_permiso'),
    path('ausencias/', views.ausencias_encargado, name='ausencias_encargado'),
    path('asistencias/', views.asistencias_encargado, name='asistencias_encargado'),
    path('send-ausencias/', views.enviar_ausencias, name='enviar_ausencias'),
    path('listar-usuarios/', views.ver_usuarios, name='listar_usuarios'),
    path('fecha-corte/', views.fecha_corte, name='fecha_corte'),
    path('listar-fecha-corte/', views.listar_fechas_corte, name='listar_fecha_corte'),
    # path('/validar/', views.validar_asistencias),
    # path('sin-permiso/', views.sin_permiso, name='sin_permiso'),
    path('cambiar-password/', views.ForzarCambioPasswordView.as_view(), name='cambiar_password'),
]