# Generated by Django 5.0.14 on 2025-07-28 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marcaje', '0019_remove_empresa_sucursal_sucursal_empresa'),
        ('turnos', '0002_remove_empleado_sucursal_remove_empleado_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('cod_color', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.PositiveIntegerField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('tiene_comprobante', models.BooleanField(default=False)),
                ('estado_solicitud', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('SB', 'Subsanar'), ('R', 'Rechazada')], default='P', max_length=2)),
                ('pendiente_subsanar', models.BooleanField(default=False)),
                ('aprobacion_gerencial', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcaje.empleado')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_pagos_enviadas', to='marcaje.empleado')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.tipopagos')),
            ],
        ),
        migrations.CreateModel(
            name='PagoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.FileField(upload_to='')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.pagos')),
            ],
        ),
        migrations.CreateModel(
            name='GestionPagoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion_realizada', models.CharField(max_length=100)),
                ('revisada_por', models.CharField(max_length=100)),
                ('comentarios', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.pagos')),
            ],
        ),
    ]
