# Generated by Django 5.0.14 on 2025-07-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0019_remove_empresa_sucursal_sucursal_empresa'),
        ('turnos', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pagos',
            new_name='Pago',
        ),
        migrations.RenameModel(
            old_name='TipoPagos',
            new_name='TipoPago',
        ),
    ]
