# Generated by Django 5.0.14 on 2025-07-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_rename_pagos_pago_rename_tipopagos_tipopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='periodo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
