"""
Django settings for asistencia project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os


from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
# Directorio donde se almacenan los archivos multimedia
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t&mx7yciqn-n_%-)&#xr98h_#eh@t7=^0tekrkhfhy+6f2#hx7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.12.232', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inicio',
    'marcaje.apps.MarcajeConfig',
    'corsheaders',
    'turnos.apps.TurnosConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'marcaje.middleware.InactividadMiddleware',  # Middleware para manejar la inactividad
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django_session_timeout.middleware.SessionTimeoutMiddleware',
    'marcaje.middleware.ForzarCambioPasswordMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'asistencia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'marcaje.context_processors.empleados_a_cargo_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'asistencia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'prueba_db',
        'USER': 'sa',
        'PASSWORD': 'Pass@w0-2710',
        'HOST': 'localhost\\SQLEXPRESS',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }
}

CSRF_TRUSTED_ORIGINS = ['http://192.168.12.245:8000']
SESSION_COOKIE_SAMESITE = None
SESSION_COOKIE_SECURE = False
# Configuración de sesiones para que expiren al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Configurar un tiempo máximo de sesión (en segundos).
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True     # Que se cuente desde la última actividad
SESSION_TIMEOUT = 600                         # Tiempo de inactividad en segundos (10 minutos aquí)
# SESSION_COOKIE_AGE = 720                    # Tiempo de vida de la cookie de sesión (12 minutos aquí)

# Configuraciones de seguridad recomendadas para la cookie de sesión
# SESSION_COOKIE_SECURE = True  # Asegúrate de usar HTTPS en producción
# SESSION_COOKIE_HTTPONLY = True  # Evita que JavaScript acceda a la cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # Protección contra CSRF
SESSION_TIMEOUT_REDIRECT = 'login'  # Redirecciona al login después de que la sesión expire
SESSION_COOKIE_DOMAIN = None

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'live.smtp.mailtrap.io'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_PORT = 587
EMAIL_HOST_USER = 'api'
EMAIL_HOST_PASSWORD = '0c4c99f15b390306ad4ae79a7c055964'
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Tegucigalpa'

USE_I18N = True

USE_TZ = True

LOGIN_URL = 'login' 
LOGOUT_URL = 'login' # Redirecciona después del login exitoso
LOGIN_REDIRECT_URL = '/'  # Redirecciona después del login exitoso

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
